# Generated by Django 4.2.11 on 2025-11-09 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('manufactured', 'Manufactured'), ('in_transit', 'In transit'), ('stored', 'Stored'), ('delivered', 'Delivered'), ('custom', 'Custom')], default='custom', max_length=32)),
                ('title', models.CharField(max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracker.product')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
